import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Armata, Bacasime_Antique, Inclusive_Sans } from "next/font/google";
import "./globals.css";

const armata = Armata({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-armata"
});

const bacasime = Bacasime_Antique({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bacasime"
});

const inclusive = Inclusive_Sans({
  subsets: ["latin"],
  variable: "--font-inclusive"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${armata.variable} ${inclusive.variable} ${bacasime.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
